### ISSUE TITLE
Watch script doesn't appear to work  (OSOE-612)

### ISSUE THREAD

**Issue by scleaver** [Lombiq/Orchard-Vue.js#82] opened 2023-04-14 05:42 UTC
Moving to the latest version using NuGet and using the watch command: `"watch": "npm explore nodejs-extensions -- pnpm watch && npm explore lombiq-vuejs -- pnpm watch"`

Files don't get watched and the following occurs (build script works):

```
XXXX@MB-Pro Groups % pnpm watch                                  

> @ watch /Users/XXXX/Projects/application/src/Modules/Groups
> npm explore nodejs-extensions -- pnpm watch && npm explore lombiq-vuejs -- pnpm watch

> nodejs-extensions@0.0.1 watch /Users/XXXX/Projects/-application/src/Modules/Groups/node_modules/.nx
> run-p --print-name --continue-on-error "watch:*"

> nodejs-extensions@0.0.1 watch:styles /Users/XXXX/Projects/application/src/Modules/Groups/node_modules/.nx/package.json
> SRC=$(node scripts/get-path scss source) && nodemon --watch $SRC --ext scss --exec "pnpm build:styles" 

> nodejs-extensions@0.0.1 watch:scripts /Users/XXXX/Projects/application/src/Modules/Groups/node_modules/.nx/package.json
> SRC=$(node scripts/get-path js source) && nodemon --watch $SRC --exec "pnpm build:scripts" 

> nodejs-extensions@0.0.1 watch:styles /Users/XXXX/Projects/application/src/Modules/Groups/node_modules/.nx
> SRC=$(node scripts/get-path scss source) && nodemon --watch $SRC --ext scss --exec "pnpm build:styles"

> nodejs-extensions@0.0.1 watch:scripts /Users/XXXX/Projects/application/src/Modules/Groups/node_modules/.nx
> SRC=$(node scripts/get-path js source) && nodemon --watch $SRC --exec "pnpm build:scripts"

[nodemon] 2.0.20
[nodemon] 2.0.20
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): 
[nodemon] to restart at any time, enter `rs`
[nodemon] watching extensions: js,mjs,json
[nodemon] watching path(s): 
[nodemon] starting `pnpm build:scripts`
[nodemon] watching extensions: scss
[nodemon] starting `pnpm build:styles`

> nodejs-extensions@0.0.1 build:styles /Users/XXXX/Projects/application/src/Modules/Groups/node_modules/.nx
> SRC=$(node scripts/get-path scss source) && if-env SRC=! && echo "Skipping styles" && exit 0 || run-p --print-name --continue-on-error lint:styles compile:styles

> nodejs-extensions@0.0.1 build:scripts /Users/XXXX/Projects/application/src/Modules/Groups/node_modules/.nx
> SRC=$(node scripts/get-path js source) && if-env SRC=! && echo "Skipping scripts" && exit 0 || run-p --print-name --continue-on-error lint:scripts compile:scripts

Skipping scripts
Skipping styles
[nodemon] clean exit - waiting for changes before restart
[nodemon] clean exit - waiting for changes before restart
```

[Jira issue](https://lombiq.atlassian.net/browse/OSOE-612)

**Comment by 0liver** [comment] 2023-04-14 08:41
Thanks for reaching out, @scleaver!

It looks like you've stumbled over one of our yet-to-to issues, https://github.com/Lombiq/Orchard-Vue.js/issues/64, which is exactly about adding `watch` support.

It also looks like we haven't mentioned anywhere in the current documentation that watching for changes does not yet work.

Would you consider submitting a PR with an addition to the main _Readme.md_ that mentions this open end? Or jump on implementing the `watch` feature itself? Both would be much appreciated.

**Comment by Piedone** [comment] 2023-10-26 15:34
Closing this as a duplicate of https://github.com/Lombiq/Orchard-Vue.js/issues/64. What we should really address is that.

**Closed as completed by Piedone** 2023-10-26 15:34 UTC
Labels: bug
